name: "06 Environments"
on: workflow_dispatch
# on:
#   push:
#     branches:
#       - main
#       - dev

env: # way to add environmental variables globally to this workflow
    MONGODB_DB_NAME: gha-demo

jobs:
  test:
    environment: testing # if you put this here, it means environmental varibles should come from the environment section configured on github settings
    env:
        MONGODB_DB_USERNAME: ${{ secrets.MONGODB_DB_USERNAME }} # makes this env variabl available to only this job
        MONGODB_DB_PASSWORD: pass-1234 # makes this env variabl available to only this job
        PORT: 8080
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      
      - name: Install dependencies
        working-directory: ./02 Starting Project
        run: npm ci

      - name: Run server
        working-directory: ./02 Starting Project
        run: npm start & npx wait-on http://127.0.0.1:$PORT # Referencing the port passed as environmental varialble

      - name: Run tests
        working-directory: ./02 Starting Project
        run: npm test

      - name: Output information
        working-directory: ./02 Starting Project
        run: |
            echo "MONGODB_DB_USERNAME= ${{ env.MONGODB_DB_USERNAME }}"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo "available: ${{ env.MONGODB_DB_NAME }}"
        #   echo "unavailale: ${{ env.MONGODB_DB_USERNAME  }}"
