name: "07 Controlling Workflow"
on: workflow_dispatch
  # push:
  #   branches:
  #     - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        working-directory: ./04 Starting Project
        run: npm ci
        
      - name: Lint code
        working-directory: ./04 Starting Project
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        working-directory: ./04 Starting Project
        run: npm ci

      - name: Test code
        id: run-tests
        working-directory: ./04 Starting Project
        run: npm run test

      - name: Upload test report
        # if here means that this step should only run if the condition within is evaluated to true
        # in this case the condition is if the outcome of a previouse step is a failure 
        if: failure() && steps.run-tests.outcome == 'failure' 
        # failure() - returns true when ANY previous step of job failed. and says this step should still execute
        uses: actions/upload-artifact@v4 # save the files somewhere
        with:
          name: test-report
          path: ./04 Starting Project/test.json

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        working-directory: ./04 Starting Project
        run: npm ci

      - name: Build website
        id: build-website
        working-directory: ./04 Starting Project
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: ./04 Starting Project/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files

      - name: Output contents
        run: ls

      - name: Deploy
        run: echo "Deploying..."

  report:
    # to make sure this report job is executed after others jobs are executed
    needs: [lint, deploy]
    # meaning this job will run ONLY if any of the other jobs failed
    if: failure() 
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "Something went wrong"
          echo ${{ github }}
