name: "08 Reusable workflow"
on: workflow_call # this allows this workflow to be called by other workflows
jobs: 
    deploy:
        runs-on: ubuntu-latest
        steps: 
            - name: Ouptut information
              run: echo "Deploying & uploading"
              