name: Label Issues (Permissions Example)
on:
  issues:
    types:
      - opened

permissions: # you can set permissions here which affect all jobs
  issues: read

jobs:
  assign-label:

    # you can set permissions here which affect this specific job
    permissions:  
      issues: write

    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        if: contains(github.event.issue.title, 'bug')
        run: |
          curl -X POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
          -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H 'content-type: application/json' \
          -d '{
              "labels": ["bug"]
            }' \
          --fail